### PR TITLE
Add HTTP Auth Hook

### PR DESCRIPTION
**Pull request by dgduncan**
Adds a basic HTTP auth hook. Also for custom `Transport` and callback for functionality.

### CODE REVIEW

**Comment by dgduncan** [comment]
@mochi-co it seems that I do not have access to add labels or reviewers. It also seems that I can not update or add projects to the `hooks` repository projects section.

**Comment by mochi-co** [comment]
@dgduncan try now

**Comment by dgduncan** [comment]
@mochi-co perfect looks like it works now!

**Comment by dgduncan** [comment]
@mochi-co How do you feel about me merging this PR and tagging with `v0.0.1.PRERELEASE` ? I do not know how many people are willing to review PRs in this repository.

**Comment by werbenhu** [comment]
@dgduncan I've been quite busy lately. I will try my best to find time to review the code.

**Comment by dgduncan** [comment]
@werbenhu No worries!

**Comment by mochi-co** [comment]
@dgduncan I'm sorry for the delay on this, I've had some big life stuff going on which has taken my time. I'm happy to merge and tag this as it looks great to me!

**Comment by mochi-co** [comment]
Released as v0.0.1 pre-release :)

**Pull request merged**
